### ISSUE TITLE
Code block not working in new live preview mode.

### ISSUE THREAD

**Issue by ParkerFoo** [bennyxguo/Obsidian-Obsidianite#44]
Hi there, thank you for making this theme. 

Code block does not seem to work in live preview mode. 
The code block will not show up in live preview mode. 

Kindly refer the screenshot below: 
![image](https://user-images.githubusercontent.com/26897852/147375021-9502d81d-5505-4e4c-81c7-64340e084ec3.png)

**Comment by Plutonium-239** [comment]
facing the same problem, it is because of the theme

**Comment by eMe-404** [comment]
really like this theme but still encountering the same issue with preview mode, is there any update for this?

**Comment by JustinB555** [comment]
Just wanted to add to this.

I did some digging into the Obsidianite.css file using the dev tools (ctrl+shift+i) and found where the visual problem was. Now, I'm NOT saying that this is the permanent fix (as I haven't fully read or tested if modifying this one part breaks anything else); but changing either the _position_, _width_, _height_, or disabling the _background color_ seemed to fix it. I changed the position from **absolute** to **relative**. Now I can read my code while using the live preview feature.

_I will warn again that this was a quick fix and not fully tested for other issues._

![Obsidianite Code Block Quick Fix](https://user-images.githubusercontent.com/60529781/149725090-83388b4e-efc7-4acd-8763-3671483735c1.png)

**Comment by JustinB555** [comment]
I will add to my previous note:

Obsidian seems to really like to hold onto old .css data. I'm not 100% certain how I did it, but hard resetting it seemed to get it to take the updated .css file. 

- **Steps I did by accident:**
- Go to clear the cache data.
- Realized that I misspelled 'Obsidian' for the folder I hold all my obsidian vaults.
- Renamed it so that it is spelled correctly.
- Relaunched Obsidian and boom, all of a sudden it is working.

I don't know how I blundered into getting it to work, but it is now. I'll keep updating if anything changes.

**Comment by Plutonium-239** [comment]
Just changing the `Obsidianite.css` in your `(vault folder) > .obsidian > themes` folder works, no need to do anything else.

**Comment by bennyxguo** [comment]
Hey all, I will provide full support for live preview mode this weekend. If not latest next weekend! Thanks for all your supports!

**Comment by HoWol76** [comment]
This seems to still be an issue with the non-legacy editor. Switching to legacy mode also solves the issue.
